---
name: ServerSwitcher
description: a plugin adds a simple server switching command to your server allowing
  players to quickly switch between different servers on the network
version: 1.1.2
authors:
- iMD14
main: iMD14\ServerSwitcher\Main
api:
- 5.0.0
src-namespace-prefix: iMD14\ServerSwitcher
commands:
  server:
    description: Transfers you to a target server
    permission: serverswitcher.use
    aliases: ["go", "goto", "transfer", "pergike"]
  servers:
    description: Display available servers
    permission: serverswitcher.use
  swrconfig:
    description: Reload ServerSwitcher Config file
    permission: serverswitcher.op
permissions:
  serverswitcher.use:
    default: true
  serverswitcher.op:
    default: op
...
